### ISSUE TITLE
'hours' parameter not functioning in API call 

### ISSUE THREAD

**Issue by arnavt2955** [Solcast/solcast-api-python-sdk#47]
I am using the API to make solar irradiation calls (Get solar radiation forecasts) with a destination of (https://api.solcast.com.au/world_radiation/forecasts). However, no matter how much I change the 'hours' parameter, the result is always 1 weeks worh of data, which is way too much for my team's usage....

Is there a way to fix this or should I correct something? I have attached a picture of our call:
![image](https://github.com/user-attachments/assets/92e83a00-3601-4e26-81bc-e1a1b5e152ba)

**Comment by billy-solcast** [comment]
Hi @arnavt2955 I haven't been able to replicate your issue.

Can you please reach out to me at support@solcast.com and I'll look up your account details and logs to see if I can diagnose your issues further.
