### ISSUE TITLE
End time for historical data

### ISSUE THREAD

**Issue by AdamRJensen** [Solcast/solcast-api-python-sdk#6]
Is it correctly assessed that it is not possible to specify the end time for historical data? For example, if I'm only interested in data from 2020.

https://github.com/Solcast/solcast-api-python-sdk/blob/00c44db6c1fdd5392b9c599c0cf85f745408ca33/solcast/historic.py#L19-L27

**Comment by lorenzo-solcast** [comment]
hi Adam, it is possible to specify an `end` parameter or a `duration` parameter in the historical query. The docstring refers back to the [API docs](https://docs.solcast.com.au/#9de907e7-a52f-4993-a0f0-5cffee78ad10) for a detailed list of parameters.

We have an example of using `period` in [this notebook in the docs](https://solcast.github.io/solcast-api-python-sdk/notebooks/Historical%20Solar%20Radiation/).

Any advice on we could make that clearer? thanks!

**Comment by AdamRJensen** [comment]
Fair point, the documentation is indeed pretty good.

I guess I would suggest including the end parameter in the example. Feel free to close this issue.
